In [3]:
import numpy as np

In [4]:
v = np.array([1,2,4])
v

array([1, 2, 4])

In [5]:
m = np.array(
    [
        [1,2,4],
        [4,5,7]
    ]
)
m

array([[1, 2, 4],
       [4, 5, 7]])

### size: help to calculte number of element

In [ ]:
v.size 

3

In [7]:
m.size

6

### shape: help to identify dimension

In [8]:
v.shape

(3,)

In [9]:
m.shape

(2, 3)

In [11]:
m[0][0] = 22
m

array([[22,  2,  4],
       [ 4,  5,  7]])

In [12]:
m[0][0] = 'Siyam'

ValueError: invalid literal for int() with base 10: 'Siyam'

this is heppend cause numpy can work with only one data type at a time

In [13]:
cnum = np.array(
    [
        [1,3],
        [2,5]
    ],
    dtype=complex
)
cnum

array([[1.+0.j, 3.+0.j],
       [2.+0.j, 5.+0.j]])

In [14]:
x = np.arange(0,10,1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x = np.arange(0,10,2)
x

array([0, 2, 4, 6, 8])