In [1]:
import numpy as np

In [5]:
y = np.zeros(
    (3,3),
    dtype=int
)
y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
y = np.zeros(
    (5,5),
    dtype=float
)
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**ones** 

In [7]:
z = np.ones(
    (5,5),
    dtype=int
)
z

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
from numpy import random

In [12]:
m = random.rand(5,3)
m

array([[0.28338249, 0.59974044, 0.96688855],
       [0.47816774, 0.81324133, 0.1529645 ],
       [0.64220934, 0.2775088 , 0.79909038],
       [0.47802476, 0.92073516, 0.87778783],
       [0.52503291, 0.67270196, 0.07139725]])

**Diagonal**

In [15]:
y = np.diag(
    [1,2,3,4]
)
y

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])