In [1]:
import numpy as np

In [2]:
name = 'siyam hossain'

In [3]:
name[-1]

'n'

In [4]:
name[0]

's'

In [5]:
m = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
m

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
m[0]

array([1, 2, 3])

In [9]:
m[0,1]

np.int64(2)

In [10]:
m[0,0]

np.int64(1)

In [11]:
m[1,2]

np.int64(6)

In [13]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
m[ : , 1]

array([2, 5])

In [14]:
m[1,2] = 65
m

array([[ 1,  2,  3],
       [ 4,  5, 65]])