In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4,5]
mylist[1:4]

[2, 3, 4]

In [3]:
mylist[3:5]

[4, 5]

In [4]:
x = np.array(
    [1,2,3,4,5]
)
x

array([1, 2, 3, 4, 5])

In [5]:
x[1:4]

array([2, 3, 4])

In [6]:
x[3:5]

array([4, 5])

In [7]:
x[::]

array([1, 2, 3, 4, 5])

x[ start : end : step ]

In [8]:
x[::2]

array([1, 3, 5])