In [1]:
import numpy as np

In [2]:
v = np.arange(0,5)
v

array([0, 1, 2, 3, 4])

In [3]:
v*2

array([0, 2, 4, 6, 8])

In [4]:
v*5+1

array([ 1,  6, 11, 16, 21])

In [23]:
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
a*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [25]:
a+a


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [26]:
a*a

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])