In [1]:
import numpy as np

In [6]:
v = np.arange(0,5)
v

array([0, 1, 2, 3, 4])

**Dot product**

In [9]:
res = np.dot(v,v)
res

np.int64(30)

In [11]:
a = np.array(
    [
        np.arange(0,5),
        np.arange(5,10)
    ]
)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
a.shape

(2, 5)

In [17]:
np.dot(a,a)

ValueError: shapes (2,5) and (2,5) not aligned: 5 (dim 1) != 2 (dim 0)

a dimension  = 2,5
a' dimension = 2,5

a col != a' row therefore multiplication not possible

In [19]:
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

row * col : similar to matrix multiplication

In [20]:
np.dot(a,a)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])