In [1]:
import numpy as np

In [2]:
a = np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [3]:
a.shape

(5, 5)

In [4]:
a.size

25

In [7]:
a[0 , 3]

np.int64(3)

In [8]:
a[1 , 3]

np.int64(8)

a[row, col] ; 
a[:, col] print column: col

In [10]:
a[ : , 3]

array([ 3,  8, 13, 18, 23])

In [11]:
np.mean(a[ : , 3])

np.float64(13.0)

In [12]:
np.average(a[ : , 3])

np.float64(13.0)

In [13]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
a[2, : ]

array([10, 11, 12, 13, 14])

In [15]:
np.mean(a[2, : ])

np.float64(12.0)

In [18]:
np.mean(a[:,:])

np.float64(12.0)

**Minimum**

In [20]:
a[2, : ]

array([10, 11, 12, 13, 14])

In [21]:
a[2, : ].min()

np.int64(10)

In [22]:
d = np.arange(0,9)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
np.sum(d)

np.int64(36)

In [24]:
np.sum(d[:])

np.int64(36)