In [2]:
import numpy as np
from numpy import random

In [4]:
m = random.rand(3,3)
m

array([[0.48112347, 0.62804586, 0.86018723],
       [0.20254751, 0.44068326, 0.63986151],
       [0.98118322, 0.31530581, 0.91046603]])

In [6]:
m.max()

np.float64(0.9811832230403804)

help to calculate column wise max

In [7]:
m.max(axis=0)

array([0.98118322, 0.62804586, 0.91046603])

help to calculate row wise max

In [8]:
m.max(axis=1)

array([0.86018723, 0.63986151, 0.98118322])

In [9]:
m.min(axis=0)

array([0.20254751, 0.31530581, 0.63986151])

In [10]:
m.min(axis=1)

array([0.48112347, 0.20254751, 0.31530581])